# Generated by Django 5.1 on 2024-09-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_employee_daily_attendance_employee_total_days_absent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
